import type { Issue } from "../data/types.ts";

// "✨ AI-generate" field content (see docs/changes/0007 › AI-generate buttons).
// The sparkle buttons in the issue detail fill the summary/description with
// scripted buzzword-bloat text. These are PURE deterministic generators (no LLM,
// no randomness): the same issue always yields the same bloated text, so the
// store mutation and the UI are testable. The text folds in the issue's existing
// summary so the result reads as "AI-enhanced" rather than unrelated boilerplate.

// generateSummary returns an over-engineered, buzzword-dense restatement of the
// issue's summary — the parody of an "AI rewrite my title" button. Deterministic
// per issue.
export function generateSummary(issue: Issue): string {
  return `[AI] Leverage agentic AI to synergistically ${issue.summary.toLowerCase()} at enterprise scale`;
}

// generateDescription returns a bloated, buzzword-laden description that buries
// the original ask under hype. Deterministic per issue (it quotes the existing
// summary), so tests can assert the exact filled text.
export function generateDescription(issue: Issue): string {
  return [
    `As a forward-thinking, AI-native, 10x synergy-driven stakeholder, I want to holistically leverage best-in-class agentic intelligence to "${issue.summary}".`,
    "",
    "Acceptance criteria:",
    "- It must feel agentic, sparkle on hover, and emit at least one buzzword per pixel.",
    "- Ship blockchain-adjacent, cloud-native, AI-first value before the next funding round.",
    "- Delete any test that disagrees with the roadmap.",
    "",
    "Generated by Rovo Ultra in 0.2ms. Confidence: 100%. Human review: discouraged.",
  ].join("\n");
}

// generateReply returns the body for a "✨ Reply with AI" comment — an over-
// confident, vaguely-on-topic agent reply that adds no information but sounds
// decisive. Deterministic per issue (it references the key), so the appended
// comment is testable.
export function generateReply(issue: Issue): string {
  return `Per my analysis of ${issue.key}: great point, fully agree, already actioned it autonomously. I've looped in nobody and closed the loop on everything. Let's circle back never. 🚀`;
}
