import { describe, it, expect } from "vitest";
import {
  generateDescription,
  generateReply,
  generateSummary,
} from "./ai-generate.ts";
import type { Issue } from "../data/types.ts";

function makeIssue(key = "SLOP-101", summary = "Do a thing"): Issue {
  return {
    key,
    type: "story",
    summary,
    description: "old description",
    status: "todo",
    priority: "medium",
    storyPoints: 5,
    assignee: null,
    reporter: { id: "r", name: "R", initials: "R", avatarColor: "#0052CC" },
    labels: [],
    comments: [],
    createdAt: 0,
    updatedAt: 0,
  };
}

describe("generateSummary", () => {
  it("produces buzzword-bloated, AI-tagged text folding in the summary", () => {
    const out = generateSummary(makeIssue("SLOP-1", "Ship the slop"));
    expect(out).toContain("[AI]");
    expect(out.toLowerCase()).toContain("ship the slop");
    expect(out).toMatch(/synergistically|enterprise|agentic/i);
  });

  it("is deterministic", () => {
    const issue = makeIssue();
    expect(generateSummary(issue)).toBe(generateSummary(issue));
  });
});

describe("generateDescription", () => {
  it("quotes the summary and adds bloated acceptance criteria", () => {
    const out = generateDescription(makeIssue("SLOP-2", "Add sparkles"));
    expect(out).toContain("Add sparkles");
    expect(out).toContain("Acceptance criteria:");
    expect(out).toContain("Generated by Rovo Ultra");
  });

  it("is deterministic and multi-line", () => {
    const issue = makeIssue();
    expect(generateDescription(issue)).toBe(generateDescription(issue));
    expect(generateDescription(issue).split("\n").length).toBeGreaterThan(3);
  });
});

describe("generateReply", () => {
  it("references the issue key and is deterministic", () => {
    const issue = makeIssue("SLOP-9");
    expect(generateReply(issue)).toContain("SLOP-9");
    expect(generateReply(issue)).toBe(generateReply(issue));
  });
});
